### ISSUE TITLE
Image dimensions are wrong on <1500px windows

### ISSUE THREAD

**Issue by Toinne** [HackYourFutureBEHomework/class2-project-bementor-group1#13]
The ratio of the image is incorrect resulting in squished faced.

**Steps to reproduce**

- Set window width to < 1500px
<img width="1440" alt="Schermafbeelding 2019-03-10 om 09 37 44" src="https://user-images.githubusercontent.com/2686028/54082561-317c0c00-4318-11e9-8c9d-83d599c40f70.png">

**Code path**

https://github.com/HackYourFutureBEHomework/class2-project-bementor-group1/blob/37067f0e6b67b262e5bb82905744ef8b99c2aebe/client/src/assets/css/index.css#L118-L119

**Comment by JoeCamacho** [comment]
Fixed
