### ISSUE TITLE
Set poppins font as default

### ISSUE THREAD

**Issue by Toinne** [HackYourFutureBEHomework/class2-project-bementor-group1#14]
If everything in the container should have this font. You can set only 1 rule instead of defining it on each element.

https://github.com/HackYourFutureBEHomework/class2-project-bementor-group1/blob/4ed9af33166f9c61ad137b3d0f93cc6f39c8922c/client/src/assets/css/index.css#L85

https://github.com/HackYourFutureBEHomework/class2-project-bementor-group1/blob/4ed9af33166f9c61ad137b3d0f93cc6f39c8922c/client/src/assets/css/index.css#L111

https://github.com/HackYourFutureBEHomework/class2-project-bementor-group1/blob/4ed9af33166f9c61ad137b3d0f93cc6f39c8922c/client/src/assets/css/index.css#L111

**Comment by JoeCamacho** [comment]
Fixed :)
